feat(bin): use `anyhow` for error reporting
It will display errors in more useful ways such as the following:

    $ cargo run ... > /dev/urandom
    Error: Failed to write the output to the standard output
    
    Caused by:
        Operation not permitted (os error 1)

    $ cargo run --release nonexistent
    Error: Failed to read an input image from 'nonexistent'
    
    Caused by:
        No such file or directory (os error 2)